app:
    resource: '@AppBundle/Controller/'
    type: annotation

login:
    path: /login
    defaults: {_controller: AppBundle:Default:login}

login_check:
    path: /login_check

logout:
    path: /logout